/**
 * Copies the canonical single-file app into the XrmToolBox plugin output folder.
 *
 * SINGLE SOURCE OF TRUTH:  ../webresource/prx3_FunctionalLocationMerge.html
 *
 * There is deliberately NO build-time skinning step any more.
 * The HTML detects its host at runtime (window.XTB_CONFIG -> XrmToolBox,
 * window.dataverseAPI -> Power Platform ToolBox, Xrm / same-origin -> D365 web
 * resource), sets body[data-host], and its Fluent 2 token block carries a palette
 * for each host:
 *
 *   body[data-host="web"]    Fluent light  (D365 web resource / standalone)
 *   body[data-host="xtb"]    Fluent light  (XrmToolBox)
 *   body[data-host="pptb"]   Fluent dark   (Power Platform ToolBox is a dark shell)
 *
 * One stylesheet instead of three that drift apart.
 *
 * Output: FunctionalLocationMerge/app/functional-location-dedup.html
 *         (bundled next to the dll by the .csproj)
 *
 * The filename must stay UNIQUE. Every XrmToolBox plugin dll lands flat in Plugins,
 * so every WebView2 tool maps its virtual host onto the SAME Plugins/app folder - a
 * generic index.html there is silently overwritten by whichever tool installs last.
 * Run:    node build-app.js
 */
const fs = require("fs");
const path = require("path");

const root = __dirname;
const src = path.join(root, "..", "webresource", "prx3_FunctionalLocationMerge.html");
const outDir = path.join(root, "FunctionalLocationMerge", "app");
const out = path.join(outDir, "functional-location-dedup.html");

if (!fs.existsSync(src)) throw new Error("Canonical HTML not found: " + src);

let html = fs.readFileSync(src, "utf8");
html = html.replace(
  "<title>",
  "<!-- XrmToolBox build - generated by xrmtoolbox/build-app.js from webresource/prx3_FunctionalLocationMerge.html -->\n<title>"
);

fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(out, html, "utf8");
console.log("XrmToolBox app written ->", path.relative(root, out), "(" + html.length + " bytes)");
